name: Publish Package

on:
  push:
    tags:
      - "*"

permissions:
  id-token: write # Required for OIDC

jobs:
  publish:
    runs-on: ubuntu-latest
      environment: Release
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Publish
          uses: anguyen-yext2/slapshot-reusable-workflows-test/publish.yml@v1